#!/bin/bash

# Settable Makefile variables
MAKE_AM_TRAIN_CORPUS_NAME=poleval-train-0.0.0
MAKE_AM_TRAIN_LM_NAME=lm-poleval-train-0.1.0

MAKE_AM_TRAIN_TRI1_LEAVES=3000
MAKE_AM_TRAIN_TRI1_PDFS=15000

MAKE_AM_TRAIN_TRI2_LEAVES=3000
MAKE_AM_TRAIN_TRI2_PDFS=15000

MAKE_AM_TRAIN_TDNN_EPOCHS=4
MAKE_AM_TRAIN_TDNN_SPLICE_INDEXES="-4,-3,-2,-1,0,1,2,3,4_0_-2,2_0_-4,4_0"
MAKE_AM_TRAIN_TDNN_SPLICE_INDEXES_VERSION=0.0.0
MAKE_AM_TRAIN_TDNN_FEAT_TYPE=mfcchighres
MAKE_AM_TRAIN_TDNN_DELTAS_DIM=0
MAKE_AM_TRAIN_TDNN_CMN=true
MAKE_AM_TRAIN_TDNN_CVN=false
MAKE_AM_TRAIN_TDNN_INITIAL_LR=0.005
MAKE_AM_TRAIN_TDNN_FINAL_LR=0.0005
MAKE_AM_TRAIN_TDNN_PNORM_INPUT_DIM=4000
MAKE_AM_TRAIN_TDNN_PNORM_OUTPUT_DIR=400

MAKE_AM_TRAIN_DISCR_TDNN_CORPUS_NAME=poleval-train-0.0.0-10p-subset
MAKE_AM_TRAIN_DISCR_TDNN_LM_NAME=lm-poleval-train-0.1.0

MAKE_PARAMS=$1

# Variables parsing
MAKE_VARIABLES=$(set | grep MAKE |\
    grep -v "MAKE_PARAMS" |\
    grep -v "MAKE_VARIABLES" |\
    grep -v "MAKE_TARGET" | perl -ne 'print "$1 " if /MAKE_(.*)/')

# Makefile target for this job
MAKE_TARGET=am-train-discr-tdnn

echo -e "Launching job: remake ${MAKE_TARGET} ${MAKE_VARIABLES} ${MAKE_PARAMS}"
remake ${MAKE_TARGET} ${MAKE_VARIABLES} ${MAKE_PARAMS}
